#version: '3.8'
##name: 'lab-files-mongodb'
#services:
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb_container
#    ports:
#      - "27017:27017"
#    environment:
##      MONGO_INITDB_USERNAME: user
##      MONGO_INITDB_PASSWORD: pass
#      MONGO_INITDB_DATABASE: mongodb
#    command: mongod --auth
#    volumes:
#      - ./data:/data/db
##      - ./data:/data/init-mongo.js
#

version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data/db  # Используем анонимный volume
    ports:
      - "27017:27017"
    command: ["/usr/bin/mongod", "--bind_ip_all"]  # Убираем --auth и передаем только --bind_ip_all

volumes:
  data:

